/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.cc-images-table[_ngcontent-%COMP%] {\r\n    \r\n}\r\n.cc-images-table[_ngcontent-%COMP%]   .files[_ngcontent-%COMP%] {\r\n    display: inline-block;\r\n    margin: 0.25em;\r\n    margin-bottom: 0.5em;\r\n}'];