/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.cc-collectible-create[_ngcontent-%COMP%] {\r\n    position: relative;\r\n}\r\n.cc-collectible-create[_ngcontent-%COMP%]   .col-xs-12.upload[_ngcontent-%COMP%] {\r\n    margin-top: 0.5em;\r\n}\r\n.cc-collectible-create[_ngcontent-%COMP%]   .row.save[_ngcontent-%COMP%] {\r\n    margin-top: 0.5em;\r\n}\r\n\r\n.cc-collectible-create[_ngcontent-%COMP%]   .success[_ngcontent-%COMP%] {\r\n    border: 1px solid #888888;\r\n    border-radius: 4px;\r\n    position: absolute;\r\n    left: -8px;\r\n    right: -8px;\r\n    top: -8px;\r\n    bottom: -8px;\r\n    background-color: rgba(0, 0, 0, 0.25);\r\n    z-index: 1000;\r\n}\r\n.cc-collectible-create[_ngcontent-%COMP%]   span.fa.fa-check[_ngcontent-%COMP%] {\r\n    font-size: 6em;\r\n    color: #00ff00;\r\n    text-shadow: 4px 4px 8px #000000;\r\n}'];