/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.cc-routes-admin-home[_ngcontent-%COMP%] {\r\n}\r\n.cc-routes-admin-home[_ngcontent-%COMP%]   .row.main[_ngcontent-%COMP%] {\r\n	margin-top: 1em;\r\n}\r\n.cc-routes-admin-home[_ngcontent-%COMP%]   .row.main[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%] {\r\n	margin-bottom: 1em;\r\n}\r\n\r\n.cc-routes-admin-home[_ngcontent-%COMP%]   .users.widget[_ngcontent-%COMP%] { }\r\n.cc-routes-admin-home[_ngcontent-%COMP%]   .users.widget[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\r\n    padding-top: 0;\r\n    margin-top: 0;\r\n}\r\n\r\n.cc-routes-admin-home[_ngcontent-%COMP%]   .collectibles.widget[_ngcontent-%COMP%] {\r\n    margin-top: 2em;\r\n}\r\n.cc-routes-admin-home[_ngcontent-%COMP%]   .collectibles.widget[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\r\n    padding-top: 0;\r\n    margin-top: 0;\r\n}'];