/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.cc-pagination[_ngcontent-%COMP%] {\r\n    \r\n}\r\n.cc-pagination[_ngcontent-%COMP%]   ul.pagination[_ngcontent-%COMP%] {\r\n    margin: 0;\r\n}\r\n.cc-pagination[_ngcontent-%COMP%]   ul.pagination[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\r\n    cursor: pointer;\r\n}'];