/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.cc-collectible-edit[_ngcontent-%COMP%] {\r\n    position: relative;\r\n}\r\n.cc-collectible-edit[_ngcontent-%COMP%]   textarea[_ngcontent-%COMP%] {\r\n    height: 6em;\r\n}\r\n.cc-collectible-edit[_ngcontent-%COMP%]   .col-xs-12.upload[_ngcontent-%COMP%] {\r\n    margin-top: 0.5em;\r\n}\r\n.cc-collectible-edit[_ngcontent-%COMP%]   .row.save[_ngcontent-%COMP%] {\r\n    margin-top: 0.5em;\r\n}\r\n.cc-collectible-edit[_ngcontent-%COMP%]   span.fa.fa-check[_ngcontent-%COMP%] {\r\n    color: #00ff00;\r\n    text-shadow: 4px 4px 8px #000000;\r\n}\r\n.cc-collectible-edit[_ngcontent-%COMP%]   span.fa.fa-remove[_ngcontent-%COMP%] {\r\n    color: #ff0000;\r\n    text-shadow: 4px 4px 8px #000000;\r\n}'];