/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.cc-collectibles-table[_ngcontent-%COMP%] {\r\n    \r\n}\r\n.cc-collectibles-table[_ngcontent-%COMP%]   .loaded-inner[_ngcontent-%COMP%] {\r\n    width: 100%;\r\n}\r\n.cc-collectibles-table[_ngcontent-%COMP%]   .collectibles[_ngcontent-%COMP%] {\r\n    display: inline-block;\r\n    margin: 0.2em;\r\n    padding: 0.2em;\r\n    border: 1px solid #f8f8f8;\r\n    background-color: #ffffff;\r\n    border-radius: 4px;\r\n    box-shadow: 1px 1px 2px #aaaaaa;\r\n}\r\n.cc-collectibles-table[_ngcontent-%COMP%]   .collectibles[_ngcontent-%COMP%]   .cc-file-thumbnail[_ngcontent-%COMP%] {\r\n\r\n}\r\n.cc-collectibles-table[_ngcontent-%COMP%]   .collectibles[_ngcontent-%COMP%]   cc-collectibles-thumbnail[_ngcontent-%COMP%] {\r\n}'];