/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.cc-site-alert[_ngcontent-%COMP%] {\r\n	\r\n}\r\n.cc-site-alert[_ngcontent-%COMP%]   .close-button[_ngcontent-%COMP%] {\r\n	float: right;\r\n}\r\n.cc-site-alert[_ngcontent-%COMP%]   .alert-danger[_ngcontent-%COMP%]   .close-button[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\r\n	font-size: 0.9em;\r\n	background: linear-gradient(to bottom, #ffe0e0, #ffb0b0);\r\n	border: 1px solid #ffa0a0;\r\n	border-radius: 2px;\r\n	color: #ff0000;\r\n}\r\n.cc-site-alert[_ngcontent-%COMP%]   .alert-success[_ngcontent-%COMP%]   .close-button[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\r\n	font-size: 0.9em;\r\n	background: linear-gradient(to bottom, #d0f0d0, #a0f0a0);\r\n	border: 1px solid #09f009;\r\n	border-radius: 2px;\r\n	color: #00a000;\r\n}'];