/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.cc-routes-users-profile[_ngcontent-%COMP%] {\r\n	\r\n}\r\n.cc-routes-users-profile[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\r\n	max-width: 10em;\r\n}\r\n.cc-routes-users-profile[_ngcontent-%COMP%]   .row.files[_ngcontent-%COMP%] {\r\n    margin-top: 1em;\r\n}\r\n.cc-routes-users-profile[_ngcontent-%COMP%]   .row.collectibles[_ngcontent-%COMP%] {\r\n    margin-top: 2em;\r\n}\r\n.cc-routes-users-profile[_ngcontent-%COMP%]   .row.collectibles[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\r\n    margin-top: 0;\r\n    padding-top: 0;\r\n}'];